/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiTestBucketRouteImport } from './routes/api/test-bucket'
import { Route as ApiSetupRouteImport } from './routes/api/setup'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiRecordsModuleRouteImport } from './routes/api/records.$module'
import { Route as ApiFilesKeyRouteImport } from './routes/api/files.$key'
import { Route as ApiRecordsModuleIdRouteImport } from './routes/api/records.$module.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestBucketRoute = ApiTestBucketRouteImport.update({
  id: '/api/test-bucket',
  path: '/api/test-bucket',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSetupRoute = ApiSetupRouteImport.update({
  id: '/api/setup',
  path: '/api/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecordsModuleRoute = ApiRecordsModuleRouteImport.update({
  id: '/api/records/$module',
  path: '/api/records/$module',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesKeyRoute = ApiFilesKeyRouteImport.update({
  id: '/api/files/$key',
  path: '/api/files/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecordsModuleIdRoute = ApiRecordsModuleIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiRecordsModuleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/setup': typeof ApiSetupRoute
  '/api/test-bucket': typeof ApiTestBucketRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/files/$key': typeof ApiFilesKeyRoute
  '/api/records/$module': typeof ApiRecordsModuleRouteWithChildren
  '/api/records/$module/$id': typeof ApiRecordsModuleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/setup': typeof ApiSetupRoute
  '/api/test-bucket': typeof ApiTestBucketRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/files/$key': typeof ApiFilesKeyRoute
  '/api/records/$module': typeof ApiRecordsModuleRouteWithChildren
  '/api/records/$module/$id': typeof ApiRecordsModuleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/setup': typeof ApiSetupRoute
  '/api/test-bucket': typeof ApiTestBucketRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/files/$key': typeof ApiFilesKeyRoute
  '/api/records/$module': typeof ApiRecordsModuleRouteWithChildren
  '/api/records/$module/$id': typeof ApiRecordsModuleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/health'
    | '/api/setup'
    | '/api/test-bucket'
    | '/api/upload'
    | '/api/files/$key'
    | '/api/records/$module'
    | '/api/records/$module/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/health'
    | '/api/setup'
    | '/api/test-bucket'
    | '/api/upload'
    | '/api/files/$key'
    | '/api/records/$module'
    | '/api/records/$module/$id'
  id:
    | '__root__'
    | '/'
    | '/api/health'
    | '/api/setup'
    | '/api/test-bucket'
    | '/api/upload'
    | '/api/files/$key'
    | '/api/records/$module'
    | '/api/records/$module/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiSetupRoute: typeof ApiSetupRoute
  ApiTestBucketRoute: typeof ApiTestBucketRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiFilesKeyRoute: typeof ApiFilesKeyRoute
  ApiRecordsModuleRoute: typeof ApiRecordsModuleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test-bucket': {
      id: '/api/test-bucket'
      path: '/api/test-bucket'
      fullPath: '/api/test-bucket'
      preLoaderRoute: typeof ApiTestBucketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/setup': {
      id: '/api/setup'
      path: '/api/setup'
      fullPath: '/api/setup'
      preLoaderRoute: typeof ApiSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/records/$module': {
      id: '/api/records/$module'
      path: '/api/records/$module'
      fullPath: '/api/records/$module'
      preLoaderRoute: typeof ApiRecordsModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$key': {
      id: '/api/files/$key'
      path: '/api/files/$key'
      fullPath: '/api/files/$key'
      preLoaderRoute: typeof ApiFilesKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/records/$module/$id': {
      id: '/api/records/$module/$id'
      path: '/$id'
      fullPath: '/api/records/$module/$id'
      preLoaderRoute: typeof ApiRecordsModuleIdRouteImport
      parentRoute: typeof ApiRecordsModuleRoute
    }
  }
}

interface ApiRecordsModuleRouteChildren {
  ApiRecordsModuleIdRoute: typeof ApiRecordsModuleIdRoute
}

const ApiRecordsModuleRouteChildren: ApiRecordsModuleRouteChildren = {
  ApiRecordsModuleIdRoute: ApiRecordsModuleIdRoute,
}

const ApiRecordsModuleRouteWithChildren =
  ApiRecordsModuleRoute._addFileChildren(ApiRecordsModuleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiSetupRoute: ApiSetupRoute,
  ApiTestBucketRoute: ApiTestBucketRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiFilesKeyRoute: ApiFilesKeyRoute,
  ApiRecordsModuleRoute: ApiRecordsModuleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
